use_default_settings: true

general:
  debug: false
  instance_name: "SearxNG"

search:
  safe_search: 0
  default_lang: "en"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "changeme-secret-key"
  limiter: false
  public_instance: false

outgoing:
  request_timeout: 3.0
  useragent_suffix: ""